name: Sphinx Problem Matcher
description: Attaches a problem matcher that looks for errors during Sphinx builds
author: Ammar Askar
branding:
  icon: book
  color: yellow
runs:
  using: 'docker'
  image: 'Dockerfile
